server:
  port: 8090

logging:
  level:
    root: error

spring:
#  datasource:
#    url: jdbc:postgresql://<ip>:<port>/<databaseName>
#    username: username
#    password: password
#    hikari:
#      auto-commit: false
#  jpa:
#    database: POSTGRESQL
#    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#    show-sql: false
  datasource:
    #    url: jdbc:h2:file:./target/h2db/db/local;DB_CLOSE_DELAY=-1
    url: jdbc:mysql://localhost:3306/cfa104g2?serverTimezone=Asia/Taipei
    username: root
    password:
    hikari:
      auto-commit: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true