server:
  port: 8080

logging:
  level:
    root: info
#info 就是default的

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
    remote:
      restart:
        enabled: false
  datasource:
#    url: jdbc:h2:file:./target/h2db/db/local;DB_CLOSE_DELAY=-1
    url: jdbc:mysql://localhost:3306/cfa104g2?serverTimezone=Asia/Taipei
    username: root
    password:
    hikari:
      auto-commit: false
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

#jsp設定(暫時不做)
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp